export const actionTypes = {
  FETCH_MEMBERS_COMPLETED: "FETCH_MEMBERS_COMPLETED",
  FETCH_MEMBER_BY_ID_COMPLETED: "FETCH_MEMBER_BY_ID_COMPLETED",
  UPDATE_MEMBER_FIELD: "UPDATE_MEMBER_FIELD",
  SAVE_MEMBER: "SAVE_MEMBER",
  FETCH_REPOSITORIES_COMPLETED: "FETCH_REPOSITORIES_COMPLETED",
  FETCH_TRANSACTION_BY_ID_COMPLETED: "FETCH_TRANSACTION_BY_ID_COMPLETED",
  FETCH_TRANSACTIONS_COMPLETED: "FETCH_TRANSACTIONS_COMPLETED",
  SEND_SOUND_COMPLETED: "SEND_SOUND_COMPLETED",
  RECEIVE_SOUND_COMPLETED: "RECEIVE_SOUND_COMPLETED",
  SAVE_TRANSACTION: "SAVE_TRANSACTION"
};
